server:
  port: 8081
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://124.222.59.109:3306/Leyou?characterEncoding=utf-8
    username: root
    password: 19961220
  application:
    name: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.pojo